import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { AppSettings, DailyLog } from '../types';

/** Build an HTML string for the doctor report */
function buildReportHtml(
  settings: AppSettings,
  logs: DailyLog[],
  fromDate: string,
  toDate: string
): string {
  const rowsHtml = logs
    .filter((l) => l.date >= fromDate && l.date <= toDate)
    .sort((a, b) => a.date.localeCompare(b.date))
    .map((log) => {
      const cells = settings.symptoms
        .map((s) => {
          const entry = log.entries.find((e) => e.symptomId === s.id);
          const sev = entry?.severity ?? '\u2014';
          return `<td style="text-align:center">${sev}</td>`;
        })
        .join('');
      const note = log.note ? `<em style="color:#666">${log.note}</em>` : '';
      return `<tr><td>${log.date}</td>${cells}<td>${note}</td></tr>`;
    })
    .join('');

  const headerCells = settings.symptoms.map((s) => `<th>${s.name}</th>`).join('');

  return `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="UTF-8" />
    <style>
      body { font-family: -apple-system, Helvetica, Arial, sans-serif; font-size: 12px; color: #222; padding: 24px; }
      h1 { font-size: 20px; color: #7C5CBF; margin-bottom: 4px; }
      .subtitle { font-size: 12px; color: #888; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; margin-top: 16px; }
      th { background: #7C5CBF; color: #fff; padding: 8px 6px; text-align: left; font-size: 11px; }
      td { border-bottom: 1px solid #E0D7F5; padding: 7px 6px; font-size: 11px; }
      tr:nth-child(even) { background: #F5F3FF; }
      .legend { margin-top: 20px; font-size: 10px; color: #888; }
      .footer { margin-top: 32px; font-size: 10px; color: #aaa; border-top: 1px solid #E0D7F5; padding-top: 8px; }
    </style>
  </head>
  <body>
    <h1>Ebb \u2014 Symptom Report</h1>
    <div class="subtitle">
      Period: ${fromDate} to ${toDate} &nbsp;\u00b7&nbsp;
      Symptoms tracked: ${settings.symptoms.map((s) => s.name).join(', ')}
    </div>
    <table>
      <thead><tr><th>Date</th>${headerCells}<th>Note</th></tr></thead>
      <tbody>${rowsHtml}</tbody>
    </table>
    <div class="legend">Severity scale: 1 = Mild &nbsp; 2 = Low &nbsp; 3 = Moderate &nbsp; 4 = High &nbsp; 5 = Severe</div>
    <div class="footer">Generated by Ebb \u00b7 ${new Date().toLocaleDateString()}</div>
  </body>
  </html>
  `;
}

/**
 * Generate and share a PDF doctor report.
 * @param settings App settings (for symptom names)
 * @param logs All daily logs (will be filtered by date range)
 * @param fromDate YYYY-MM-DD
 * @param toDate YYYY-MM-DD
 */
export async function exportPdf(
  settings: AppSettings,
  logs: DailyLog[],
  fromDate: string,
  toDate: string
): Promise<void> {
  const html = buildReportHtml(settings, logs, fromDate, toDate);
  const { uri } = await Print.printToFileAsync({ html, base64: false });

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: 'Share Ebb Report',
      UTI: 'com.adobe.pdf',
    });
  }
}
